config/routes.rb
Task4::Application.routes.draw do
  devise_for :users
  resources :todos, :only => [:new, :index, :create]
  root :to => "todos#index"

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_filter :authenticate_user!, :except => [:index]
    def index
      @todos = Todo.all
    end
    
    def new
      @todo = Todo.new
    end
    
    def create
      @todo = Todo.new(params[:todo])
      @todo.update_attributes(:author => current_user.email)
      if @todo.save
          redirect_to todos_path
      else
          render :action => :new
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task4</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>-->

<!-- layouts/application.html.erb -->
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

</body>
</html>

app/views/todos/index.html.haml
- @todos.each do |todo|
  %p
    %b= todo.author
    %br
    = todo.description
  %hr
%p= link_to "Dodaj nowe TODO", new_todo_path

app/views/todos/new.html.haml
- form_for @todo do |f|
  %p
    Opis
    %br
    = f.text_area :description
  
  %p=f.submit "Dodaj"
%p= link_to "Powrót do listy TODO", todos_path